# Generated by Django 5.2.17 on 2026-09-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_or_stage_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='contact_number',
            field=models.CharField(blank=True, default='+63', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='district',
            field=models.CharField(choices=[('cebu_city', 'Cebu City'), ('mandaue', 'Mandaue City'), ('lapu_lapu', 'Lapu-Lapu City'), ('talisay', 'Talisay City')], default='cebu_city', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
    ]
