# Generated by Django 5.2.17 on 2026-09-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AddField(
            model_name='usersettings',
            name='public_profile',
            field=models.BooleanField(default=False),
        ),
    ]
