# Generated by Django 5.2.17 on 2026-09-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('role_type', models.CharField(choices=[('ENTERTAINMENT', 'Live entertainment'), ('MEDIA', 'Media coverage'), ('OPERATIONS', 'Operations')], max_length=15)),
                ('description', models.TextField(blank=True, default='')),
                ('slots_total', models.PositiveSmallIntegerField(default=1)),
                ('pay_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('call_time', models.DateTimeField(blank=True, null=True)),
                ('apply_by', models.DateField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_roles', to='events.event')),
            ],
            options={
                'verbose_name': 'Gig Role',
                'verbose_name_plural': 'Gig Roles',
                'ordering': ['event', 'apply_by'],
            },
        ),
        migrations.CreateModel(
            name='GigApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cover_note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_applications', to=settings.AUTH_USER_MODEL)),
                ('gig_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gigs.gigrole')),
            ],
            options={
                'verbose_name': 'Gig Application',
                'verbose_name_plural': 'Gig Applications',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='gigrole',
            index=models.Index(fields=['is_open'], name='gigs_gigrol_is_open_1d6820_idx'),
        ),
        migrations.AddIndex(
            model_name='gigapplication',
            index=models.Index(fields=['status'], name='gigs_gigapp_status_e67174_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gigapplication',
            unique_together={('gig_role', 'applicant')},
        ),
    ]
