# Generated by Django 5.2.17 on 2026-09-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('permits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoothTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('booth_category', models.CharField(choices=[('DRY_GOODS', 'Dry goods / crafts'), ('HOT_COOKING', 'Hot cooking'), ('BEVERAGE', 'Beverage station'), ('ART_INSTALL', 'Interactive art installation')], max_length=20)),
                ('max_width_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_depth_m', models.DecimalField(decimal_places=2, max_digits=5)),
                ('power_watts', models.PositiveIntegerField(default=0, help_text='0 means no power provided.')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('slots_total', models.PositiveSmallIntegerField(default=1)),
                ('guidelines', models.TextField(blank=True, default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_tiers', to='events.event')),
                ('required_permits', models.ManyToManyField(blank=True, related_name='booth_tiers', through='permits.BoothTierRequirement', to='permits.permittype')),
            ],
            options={
                'verbose_name': 'Booth Tier',
                'verbose_name_plural': 'Booth Tiers',
                'ordering': ['event', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BoothApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.TextField(help_text='Menu or product range.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='PENDING', max_length=12)),
                ('organizer_notes', models.TextField(blank=True, default='')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_applications', to=settings.AUTH_USER_MODEL)),
                ('booth_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vendors.boothtier')),
            ],
            options={
                'verbose_name': 'Booth Application',
                'verbose_name_plural': 'Booth Applications',
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['status'], name='vendors_boo_status_6bdb3b_idx')],
                'unique_together': {('booth_tier', 'vendor')},
            },
        ),
    ]
