# Generated by Django 5.2.17 on 2026-09-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoothTierRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Booth Tier Requirement',
                'verbose_name_plural': 'Booth Tier Requirements',
                'db_table': 'permits_boothtierrequirement',
            },
        ),
        migrations.CreateModel(
            name='EventPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REQUIRED', 'Required'), ('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='REQUIRED', max_length=15)),
                ('reference_no', models.CharField(blank=True, default='', max_length=60)),
                ('document', models.FileField(blank=True, null=True, upload_to='permits/events/')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Event Permit',
                'verbose_name_plural': 'Event Permits',
            },
        ),
        migrations.CreateModel(
            name='PermitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('issuing_office', models.CharField(max_length=150)),
                ('scope', models.CharField(choices=[('EVENT', 'Event-level'), ('VENDOR', 'Vendor-level')], max_length=10)),
                ('trigger_rule', models.CharField(choices=[('ALWAYS', 'Always required'), ('HAS_FOOD', 'Required when the event has food stalls'), ('ROAD_CLOSURE', 'Required when the event closes roads'), ('TICKETED', 'Required when the event is ticketed')], default='ALWAYS', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Permit Type',
                'verbose_name_plural': 'Permit Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VendorCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, default='', max_length=60)),
                ('document', models.FileField(blank=True, null=True, upload_to='permits/vendors/')),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('EXPIRED', 'Expired')], default='PENDING', max_length=15)),
            ],
            options={
                'verbose_name': 'Vendor Compliance',
                'verbose_name_plural': 'Vendor Compliance Records',
            },
        ),
    ]
