# Generated by Django 5.2.17 on 2026-09-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('permits', '0001_initial'),
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boothtierrequirement',
            name='booth_tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_requirements', to='vendors.boothtier'),
        ),
        migrations.AddField(
            model_name='eventpermit',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventpermit',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_permits', to='permits.permittype'),
        ),
        migrations.AddField(
            model_name='boothtierrequirement',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tier_requirements', to='permits.permittype'),
        ),
        migrations.AddField(
            model_name='vendorcompliance',
            name='permit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_compliance_records', to='permits.permittype'),
        ),
        migrations.AddField(
            model_name='vendorcompliance',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventpermit',
            index=models.Index(fields=['status'], name='permits_eve_status_321c15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eventpermit',
            unique_together={('event', 'permit_type')},
        ),
        migrations.AlterUniqueTogether(
            name='boothtierrequirement',
            unique_together={('booth_tier', 'permit_type')},
        ),
        migrations.AlterUniqueTogether(
            name='vendorcompliance',
            unique_together={('vendor', 'permit_type')},
        ),
    ]
