# Generated by Django 5.2.17 on 2026-10-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permittype',
            name='trigger_rule',
            field=models.CharField(choices=[('ALWAYS', 'Always required'), ('HAS_FOOD', 'Required when the event has food stalls'), ('ROAD_CLOSURE', 'Required when the event closes roads'), ('TICKETED', 'Required when the event is ticketed'), ('CROWD_100', 'Required for 100+ expected attendees'), ('CROWD_500', 'Required for 500+ expected attendees')], default='ALWAYS', max_length=30),
        ),
    ]
